services:
- docker
before_install:
- docker pull continuumio/anaconda
- git config --global user.email "uvilla@wustl.edu"
- git config --global user.name "U. Villa through Travis CI"
- git remote set-url origin https://${GH_TOKEN}@github.com/hippylib/muq-hippylib.git

script:
- docker run --rm -v $(pwd):/share -w /share continuumio/anaconda .travis/mkdocs-build.sh