services:
- docker
before_install:
- docker pull continuumio/anaconda
- git config --global user.email "uvilla@wustl.edu"
- git config --global user.name "U. Villa through Travis CI"
script:
- docker run --rm -v $(pwd):/share -w /share continuumio/anaconda .travis/mkdocs-build.sh
